npmRegistries:
  "https://nexus.eu-west-3.codefi.network/repository/npm-hosted/":
    npmAuthToken: <auth-token>

npmScopes:
  codefi:
    npmRegistryServer: "https://nexus.eu-west-3.codefi.network/repository/npm-hosted/"